### ISSUE TITLE
[ IMPLEMENT ] 0.3.x Milestone

### ISSUE THREAD

**Issue by KorewaLidesu** [JP-HellParadise/TestBridge#9]
- [x] Register item rework
- [x] Rework on GUI for reduce hard dependency (Allow mod to be universal addon)
This introduce ModularUI (require 2.1.+ which is kinda overhead other mods that depend on it for now)
- [ ] Configurable which addon allowed to load
This will prevent Mixin and Integration from loading addon in without causing other issue
- [ ] In-game config
- [ ] Rewrite Crafting Manager pipe recipe handler ([#18](https://github.com/JP-HellParadise/TestBridge/issues/18))

**Comment by KorewaLidesu** [comment]
## Changelog
<details> <summary>0.3.7 (<a href="https://github.com/JP-HellParadise/TestBridge/pull/21">#21</a>) </summary>

#### 1. Added/Implemented:
- (Gradle) Spotless (`6.20.0`)
- ModularUI (`2.1.0`): Overhaul Satellite, Package UI rework.
#### 2. Updated:
- RFG (`1.3.19` -> `1.3.24`)
- MixinBooter (`8.2` -> `8.3-prebuild`)
- Logistics Pipe (`0.10.4.44` -> `0.10.4.46`)
- AE2 Unofficial Extended Life (`0.54.15` -> `0.55.17`)
#### 3. Removed:
- EnumHelper hack. Now use Mixin to create new enum instead.
#### 4. Bug fixed:
- Container Package reset back without drop items when Sneak+R-Click on block.
- ClassNotFoundException on TextUtil class when Logistics Pipe is not installed

</details>
